CREATE TABLE dbo.Number (num SMALLINT NOT NULL CONSTRAINT PK_Number PRIMARY KEY);

WITH n AS
(
  SELECT 0 AS num
  UNION ALL
  SELECT num + 1
  FROM n
  WHERE num < 10000
)
INSERT INTO dbo.Number (num)
SELECT num
FROM n
OPTION (MAXRECURSION 0);